name: test-coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.x
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          make install
      - name: Build project
        run: |
          poetry run python manage.py migrate
      - name: Lint
        run: |
          make lint
      - name: Test coverage
        uses: paambaati/codeclimate-action@v5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_COV_ID }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        with:
          coverageCommand: make test-cov
          debug: true